"use client";

import { forwardRef, useState } from "react";
import html2canvas from "html2canvas";
import { Copy, Download, Check, RefreshCw } from "lucide-react";
import { PLACEHOLDER_HEADSHOT } from "@/lib/tmdb";
import { stripQuotes } from "@/lib/text";

interface PostCardProps {
  actorName: string;
  postText: string;
  headshotUrl: string;
}

function XLogo({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={className} fill="currentColor" aria-hidden="true">
      <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
    </svg>
  );
}

const PostCard = forwardRef<HTMLDivElement, PostCardProps>(
  ({ actorName, postText, headshotUrl }, ref) => {
    return (
      <div
        ref={ref}
        className="relative w-full max-w-2xl mx-auto rounded-2xl overflow-hidden border border-cinema-border"
        style={{
          background: "linear-gradient(135deg, #0A0A0F 0%, #1A1A2E 60%, #12121A 100%)",
        }}
      >
        <div className="relative p-5 sm:p-8 flex flex-col md:flex-row gap-5 sm:gap-6 items-center md:items-start">
          <div className="flex-shrink-0">
            <div className="inline-block rounded-2xl overflow-hidden border border-gold/20 bg-cinema-black leading-none">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={headshotUrl || PLACEHOLDER_HEADSHOT}
                alt={actorName}
                className="h-44 sm:h-52 w-auto block"
                crossOrigin="anonymous"
              />
            </div>
          </div>

          <div className="flex-1 min-w-0 flex flex-col justify-center">
            <h3 className="font-display text-gold text-xl sm:text-2xl font-semibold mb-3 sm:mb-4 tracking-wide leading-tight">
              {actorName}
            </h3>
            <p className="text-foreground/90 text-base sm:text-lg leading-relaxed font-light tracking-wide">
              {postText}
            </p>
          </div>
        </div>

        <div className="relative px-5 sm:px-8 pb-4 sm:pb-5 flex justify-end">
          <span className="text-[10px] sm:text-xs text-gray-500 tracking-widest uppercase">
            Generated by CinePost
          </span>
        </div>
      </div>
    );
  }
);

PostCard.displayName = "PostCard";

export default PostCard;

export function PostCardActions({
  actorName,
  postText,
  cardRef,
  onGenerateAnother,
}: Omit<PostCardProps, "headshotUrl"> & {
  cardRef: React.RefObject<HTMLDivElement | null>;
  onGenerateAnother?: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const cleanText = stripQuotes(postText);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(cleanText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShareX = () => {
    window.open(
      `https://twitter.com/intent/tweet?text=${encodeURIComponent(cleanText)}`,
      "_blank",
      "noopener,noreferrer"
    );
  };

  const handleDownload = async () => {
    if (!cardRef.current) return;
    setDownloading(true);
    try {
      const wrapper = document.createElement("div");
      wrapper.style.padding = "20px";
      wrapper.style.background = "#0A0A0F";
      wrapper.style.display = "inline-block";

      const clone = cardRef.current.cloneNode(true) as HTMLElement;
      wrapper.appendChild(clone);
      document.body.appendChild(wrapper);

      const canvas = await html2canvas(wrapper, {
        backgroundColor: "#0A0A0F",
        scale: 2,
        useCORS: true,
        allowTaint: true,
        logging: false,
        width: wrapper.offsetWidth,
        height: wrapper.offsetHeight,
      });

      document.body.removeChild(wrapper);

      const link = document.createElement("a");
      link.download = `cinepost-${actorName.toLowerCase().replace(/\s+/g, "-")}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch (err) {
      console.error("Download failed:", err);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="mt-6 space-y-3">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        <button
          onClick={handleCopy}
          className="btn-blue flex items-center justify-center gap-2 w-full"
        >
          {copied ? (
            <>
              <Check className="w-4 h-4" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="w-4 h-4" />
              Copy Post
            </>
          )}
        </button>

        <button
          onClick={handleDownload}
          disabled={downloading}
          className="btn-dark flex items-center justify-center gap-2 w-full"
        >
          <Download className="w-4 h-4" />
          {downloading ? "Downloading..." : "Download Card"}
        </button>

        <button
          onClick={handleShareX}
          className="btn-x flex items-center justify-center gap-2 w-full sm:col-span-2 lg:col-span-1"
        >
          <XLogo className="w-4 h-4" />
          Post to X
        </button>
      </div>

      {onGenerateAnother && (
        <div className="flex justify-center pt-2">
          <button
            onClick={onGenerateAnother}
            className="btn-gold flex items-center justify-center gap-2 w-full sm:w-auto"
          >
            <RefreshCw className="w-4 h-4" />
            Generate Another
          </button>
        </div>
      )}
    </div>
  );
}
