import Link from "next/link";

export const metadata = {
  title: "Terms of Service — CinePost",
  description: "Terms and conditions for using CinePost.",
};

export default function TermsPage() {
  return (
    <div className="min-h-[calc(100vh-4rem)] py-16 px-4 sm:px-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="font-display text-3xl sm:text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-10">Last updated: June 17, 2026</p>

        <div className="space-y-8 text-gray-300 text-sm leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using CinePost (&quot;the Service&quot;), you agree to be bound by these Terms
              of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p>
              CinePost is an AI-powered tool that generates social media content about actors, including
              text posts and visual cards with actor headshots. The Service is currently offered free during
              early access. Paid plans may be introduced in the future.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. Account Registration</h2>
            <p>
              You may use limited features without an account. To access full features, you must create an
              account with a valid email address and password. You are responsible for maintaining the
              confidentiality of your account credentials and for all activity under your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to circumvent usage limits or access controls</li>
              <li>Scrape, reverse engineer, or abuse the Service or its APIs</li>
              <li>Generate content that is defamatory, harassing, or violates others&apos; rights</li>
              <li>Resell or redistribute the Service without permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">5. AI-Generated Content</h2>
            <p>
              Content generated by CinePost is created by artificial intelligence and may contain
              inaccuracies. You are solely responsible for reviewing and verifying any content before
              publishing it. We do not guarantee the accuracy, originality, or suitability of generated
              content for any purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">6. Intellectual Property</h2>
            <p>
              You retain rights to content you generate using the Service, subject to applicable law and
              third-party rights (including TMDB image licenses). CinePost, its branding, and underlying
              technology remain our intellectual property. Actor headshots are sourced from TMDB and are
              subject to TMDB&apos;s terms of use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">7. Usage Limits</h2>
            <p>
              We may impose usage limits on free and guest accounts, including daily generation caps. We
              reserve the right to modify limits at any time. During early access, the Service is provided
              free of charge with no payment required.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">8. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY
              KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
              NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">9. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, CINEPOST SHALL NOT BE LIABLE FOR ANY INDIRECT,
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
              OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE PAST 12 MONTHS, OR $0
              DURING FREE EARLY ACCESS.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">10. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time for violation of these
              Terms or for any other reason. You may stop using the Service at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">11. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after changes
              constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">12. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{" "}
              <a href="mailto:hello@cinepost.com" className="text-gold hover:underline">
                hello@cinepost.com
              </a>
              .
            </p>
          </section>
        </div>

        <p className="mt-12 text-gray-500 text-sm">
          <Link href="/" className="text-gold hover:underline">
            ← Back to home
          </Link>
        </p>
      </div>
    </div>
  );
}
